### PR TITLE
Fixed some incorrect addresses

### PR DESCRIPTION
**Pull request by AnonymousRandomPerson**
While syncing NA and EU with the decomp, I ran into a number of incorrect addresses that conflicted between versions. I manually resolved each of these, attempting to favor the version that the original contributor used.

### CODE REVIEW

**Review by End45 — APPROVED** [review]
Manually checked everything except `SKY_ATTACK_DAMAGE_MULTIPLIER` and `CheckTeamMemberIdxVeneer`. The new offsets are correct.

Some of these errors are mine. I looks like they happned because of functions that are almost identical to the one that I was documenting, so I mistook them for the right one when adding the US offsets.
I need to find a better way of doing that.

**Comment by UsernameFodder** [comment]
> Manually checked everything except SKY_ATTACK_DAMAGE_MULTIPLIER and CheckTeamMemberIdxVeneer. The new offsets are correct.

The new `SKY_ATTACK_DAMAGE_MULTIPLIER` is correct (I apparently had this right in my Ghidra project, but transcribed it wrong). `CheckTeamMemberIdxVeneer` points to the new `CheckTeamMemberIdx` as would be expected.

**Review by UsernameFodder — APPROVED** [review]
Thanks!

**Comment by AnonymousRandomPerson** [comment]
> I looks like they happned because of functions that are almost identical to the one that I was documenting, so I mistook them for the right one when adding the US offsets.
I need to find a better way of doing that.

We can now use the decomp to match EU/US offsets more reliably than an ASM similarity check. For example, when knowing the EU address:
1. Find the placeholder symbol name within EU's [xMAP file](https://raw.githubusercontent.com/pret/pmd-sky/xmap/pmdskyeu.xMAP) by looking at the address and overlay.
2. Rename the symbol within the decomp.
3. Build the US ROM.
4. Find the symbol in the US xMAP file to get the US address.

I follow changes to pmdsky-debug and sync them to the decomp, so any conflicting addresses will be sorted out by this process as well.

**Comment by End45** [comment]
> > I looks like they happned because of functions that are almost identical to the one that I was documenting, so I mistook them for the right one when adding the US offsets.
> > I need to find a better way of doing that.
> 
> We can now use the decomp to match EU/US offsets more reliably than an ASM similarity check. For example, when knowing the EU address:
> 
>     1. Find the placeholder symbol name within EU's [xMAP file](https://raw.githubusercontent.com/pret/pmd-sky/xmap/pmdskyeu.xMAP) by looking at the address and overlay.
> 
>     2. Rename the symbol within the decomp.
> 
>     3. Build the US ROM.
> 
>     4. Find the symbol in the US xMAP file to get the US address.
> 
> 
> I follow changes to pmdsky-debug and sync them to the decomp, so any conflicting addresses will be sorted out by this process as well.

I might use that if I ever set up the decomp project on my computer. Right now, it's still quicker to check manually.

**Pull request merged**
