### PR TITLE
Use American spelling for "initialization"

### PR DESCRIPTION
**Pull request by AnonymousRandomPerson**
Per discussion with @End45 in https://github.com/UsernameFodder/pmdsky-debug/pull/189

### CODE REVIEW

**Comment by End45** [comment]
If we're making this change, might as well change the other 4 places where british spelling is used. All of them can be found in arm9.yml.

**Comment by AnonymousRandomPerson** [comment]
Replaced other forms of the word "initialise".

**Comment by End45** [comment]
You missed https://github.com/UsernameFodder/pmdsky-debug/blob/afe65994b451c90e99ade470674b604a3a0dfda4/symbols/arm9.yml#L1171

**Comment by AnonymousRandomPerson** [comment]
Looks fine to me 🤔. I see line 1171 changed in the diff for this PR.

**Comment by End45** [comment]
Oh, it's on the first commit so it didn't show up by default when I clicked last time. Nevermind then.

**Review by UsernameFodder — APPROVED** [review]
👍

**Pull request merged**
