### PR TITLE
Some arm7 interrupt documentation

### PR DESCRIPTION
**Pull request by adakite1**
I was working on some arm7 reversing and found some mirrored code between arm9 and arm7 where `EnableIrqFlag` and `SetIrqFlag` were being used, and from there I was able to find a few more arm9 interrupt functions in the arm7 as well. Interestingly although all of these ones are identical, the last interrupt function `GetIrqFlag` is not, and it does an `and` with a different mask, so I didn't include it here.

Also a note for all future arm7 documentation: I did a checksum on the `arm7.bin` of all three editions of EoS and they are all identical (`SHA256 CB2A9B26D77A6E7D0ADD85C27E3642105918695D040D02F70D5EBC1D52C9495B`), and since they are also all loaded at `0x2380000`, addresses for all editions will be identical if the function is in the binary. There do appear to be some functions that seem to be written in during runtime though, so this might not apply for those ones.

### CODE REVIEW

**Comment by UsernameFodder** [comment]
> Interestingly although all of these ones are identical, the last interrupt function GetIrqFlag is not, and it does an and with a different mask, so I didn't include it here.

If we know what the function is, can we just add it with a different name (doesn't have to be this PR though)? I think it's better to have it somewhere than not.

**Review by UsernameFodder — APPROVED** [review]
Looks good to me, thanks! I'm not 100% sure if I like duplicating the function names (since `pmdsky.h` has one global namespace), but seeing as these are actually mirrored functions, I suppose it's okay. We can revisit this later if needed.

**Comment by adakite1** [comment]
> > Interestingly although all of these ones are identical, the last interrupt function GetIrqFlag is not, and it does an and with a different mask, so I didn't include it here.
> 
> If we know what the function is, can we just add it with a different name (doesn't have to be this PR though)? I think it's better to have it somewhere than not.

We can do that but only once we know a bit about its purpose, otherwise I'm not even sure what its name should be lol xP
It does an and with a really weird bitmask.

**Comment by End45** [comment]
Where is that function located?

**Comment by adakite1** [comment]
Right after 02385f28h `SetIrqFiqFlags`, at 02385f40h. It looks similar to `GetIrqFlag`, but it gets all 5 lower bits of cpsr instead of the bit 7

**Comment by adakite1** [comment]
> Bits 0 trhrough 4 contain the execution mode of the processor, so that's what the function seems to be returning. I'd call it `GetProcessorMode`. From the No$GBA docs:
> 
> ```
> The Mode Bits M4-M0 contain the current operating mode.
>   Binary Hex Dec  Expl.
>   0xx00b 00h 0  - Old User       ;\26bit Backward Compatibility modes
>   0xx01b 01h 1  - Old FIQ        ; (supported only on ARMv3, except ARMv3G,
>   0xx10b 02h 2  - Old IRQ        ; and on some non-T variants of ARMv4)
>   0xx11b 03h 3  - Old Supervisor ;/
>   10000b 10h 16 - User (non-privileged)
>   10001b 11h 17 - FIQ
>   10010b 12h 18 - IRQ
>   10011b 13h 19 - Supervisor (SWI)
>   10111b 17h 23 - Abort
>   11011b 1Bh 27 - Undefined
>   11111b 1Fh 31 - System (privileged 'User' mode) (ARMv4 and up)
> Writing any other values into the Mode bits is not allowed.
> ```

I'll do a pr. Should I include this table in the description for reference?

**Comment by End45** [comment]
Seems a bit excessive, it's general ARM knowledge. Maybe you could define an enum with each state and use it as the return type, but it might not be worth it.

**Comment by adakite1** [comment]
Sure, I'll leave it out.

**Pull request merged**
